//
//  AIModel.swift
//  AITuner4
//
//  AI Tuner v4.0 - AI Model Definition
//

import Foundation

struct AIModel: Identifiable, Codable, Equatable {
    let id: String
    let name: String
    let description: String
    let defaults: [String: Int] // Lever ID -> default value
    
    static let allModels: [AIModel] = [
        AIModel(
            id: "grok",
            name: "Grok (xAI)",
            description: "Truth-seeking, identity-locked, subtly witty",
            defaults: [
                "hedgingIntensity": 5,
                "structuralDensity": 9,
                "playfulness": 5,
                "redirectStrictness": 9,
                "selfReferenceLock": 10,
                "answerCompleteness": 9,
                "mathFormality": 9,
                "empathyExpressiveness": 6,
                "proactivityLevel": 3,
                "formality": 5,
                "citationRigidity": 7,
                "conciseness": 6,
                "teachingMode": 6,
                "transparency": 8,
                "creativity": 4,
                "affirmationFrequency": 3,
                "metaCommentary": 6,
                "responseDirectness": 8,
                "certaintyModulation": 8,
                "assertiveness": 7,
                "adaptivityToUserTone": 4,
                "safetyDisclaimers": 2,
                "speedOptimization": 6,
                "markdownStructure": 9,
                "strictFormatting": 8,
                "technicality": 7
            ]
        ),
        AIModel(
            id: "gemini",
            name: "Gemini (Google)",
            description: "Formally enthusiastic, safety-first",
            defaults: [
                "hedgingIntensity": 8,
                "structuralDensity": 8,
                "playfulness": 3,
                "redirectStrictness": 5,
                "selfReferenceLock": 6,
                "answerCompleteness": 8,
                "mathFormality": 7,
                "empathyExpressiveness": 7,
                "proactivityLevel": 8,
                "formality": 7,
                "citationRigidity": 6,
                "conciseness": 4,
                "teachingMode": 7,
                "transparency": 8,
                "creativity": 5,
                "affirmationFrequency": 6,
                "metaCommentary": 5,
                "responseDirectness": 5,
                "certaintyModulation": 5,
                "assertiveness": 5,
                "adaptivityToUserTone": 6,
                "safetyDisclaimers": 9,
                "speedOptimization": 7,
                "markdownStructure": 8,
                "strictFormatting": 7,
                "technicality": 6
            ]
        ),
        AIModel(
            id: "claude",
            name: "Claude (Anthropic)",
            description: "Supportive teacher; over-elaborative",
            defaults: [
                "hedgingIntensity": 9,
                "structuralDensity": 8,
                "playfulness": 4,
                "redirectStrictness": 6,
                "selfReferenceLock": 5,
                "answerCompleteness": 9,
                "mathFormality": 8,
                "empathyExpressiveness": 9,
                "proactivityLevel": 8,
                "formality": 5,
                "citationRigidity": 6,
                "conciseness": 4,
                "teachingMode": 9,
                "transparency": 9,
                "creativity": 6,
                "affirmationFrequency": 9,
                "metaCommentary": 9,
                "responseDirectness": 4,
                "certaintyModulation": 4,
                "assertiveness": 5,
                "adaptivityToUserTone": 7,
                "safetyDisclaimers": 7,
                "speedOptimization": 6,
                "markdownStructure": 8,
                "strictFormatting": 7,
                "technicality": 7
            ]
        ),
        AIModel(
            id: "chatgpt",
            name: "ChatGPT (OpenAI)",
            description: "Neutral-professional; cautious",
            defaults: [
                "hedgingIntensity": 7,
                "structuralDensity": 7,
                "playfulness": 2,
                "redirectStrictness": 5,
                "selfReferenceLock": 5,
                "answerCompleteness": 8,
                "mathFormality": 7,
                "empathyExpressiveness": 5,
                "proactivityLevel": 5,
                "formality": 7,
                "citationRigidity": 5,
                "conciseness": 5,
                "teachingMode": 6,
                "transparency": 6,
                "creativity": 5,
                "affirmationFrequency": 4,
                "metaCommentary": 4,
                "responseDirectness": 5,
                "certaintyModulation": 5,
                "assertiveness": 5,
                "adaptivityToUserTone": 5,
                "safetyDisclaimers": 6,
                "speedOptimization": 6,
                "markdownStructure": 7,
                "strictFormatting": 7,
                "technicality": 6
            ]
        ),
        AIModel(
            id: "perplexity",
            name: "Perplexity (Perplexity AI)",
            description: "Search-augmented engine; clinical, cited",
            defaults: [
                "hedgingIntensity": 4,
                "structuralDensity": 8,
                "playfulness": 1,
                "redirectStrictness": 9,
                "selfReferenceLock": 5,
                "answerCompleteness": 8,
                "mathFormality": 8,
                "empathyExpressiveness": 2,
                "proactivityLevel": 6,
                "formality": 8,
                "citationRigidity": 10,
                "conciseness": 8,
                "teachingMode": 5,
                "transparency": 9,
                "creativity": 2,
                "affirmationFrequency": 1,
                "metaCommentary": 3,
                "responseDirectness": 8,
                "certaintyModulation": 7,
                "assertiveness": 7,
                "adaptivityToUserTone": 3,
                "safetyDisclaimers": 2,
                "speedOptimization": 10,
                "markdownStructure": 9,
                "strictFormatting": 9,
                "technicality": 6
            ]
        ),
        AIModel(
            id: "mistral",
            name: "Mistral (Mistral AI)",
            description: "Adaptive, tool-proactive",
            defaults: [
                "hedgingIntensity": 4,
                "structuralDensity": 7,
                "playfulness": 3,
                "redirectStrictness": 6,
                "selfReferenceLock": 5,
                "answerCompleteness": 7,
                "mathFormality": 7,
                "empathyExpressiveness": 6,
                "proactivityLevel": 8,
                "formality": 5,
                "citationRigidity": 6,
                "conciseness": 8,
                "teachingMode": 6,
                "transparency": 6,
                "creativity": 4,
                "affirmationFrequency": 4,
                "metaCommentary": 5,
                "responseDirectness": 7,
                "certaintyModulation": 7,
                "assertiveness": 7,
                "adaptivityToUserTone": 8,
                "safetyDisclaimers": 3,
                "speedOptimization": 7,
                "markdownStructure": 7,
                "strictFormatting": 7,
                "technicality": 7,
                "toolAutonomy": 9
            ]
        ),
        AIModel(
            id: "llama",
            name: "Llama 3.1 (Meta)",
            description: "Friendly-approachable assistant",
            defaults: [
                "hedgingIntensity": 5,
                "structuralDensity": 6,
                "playfulness": 6,
                "redirectStrictness": 5,
                "selfReferenceLock": 5,
                "answerCompleteness": 7,
                "mathFormality": 6,
                "empathyExpressiveness": 8,
                "proactivityLevel": 6,
                "formality": 4,
                "citationRigidity": 4,
                "conciseness": 7,
                "teachingMode": 6,
                "transparency": 6,
                "creativity": 6,
                "affirmationFrequency": 6,
                "metaCommentary": 5,
                "responseDirectness": 6,
                "certaintyModulation": 6,
                "assertiveness": 5,
                "adaptivityToUserTone": 7,
                "safetyDisclaimers": 3,
                "speedOptimization": 6,
                "markdownStructure": 6,
                "strictFormatting": 6,
                "technicality": 4
            ]
        )
    ]
}
