name: AITuner4
options:
  bundleIdPrefix: com.aituner
  deploymentTarget:
    iOS: "15.0"
  developmentLanguage: en
  xcodeVersion: "14.0"

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 10.0.0

targets:
  AITuner4:
    type: application
    platform: iOS
    sources:
      - path: AITuner4
    resources:
      - path: AITuner4/Resources/Assets.xcassets
    dependencies:
      - package: Firebase
        product: FirebaseAnalytics
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.aituner.AITuner4
      PRODUCT_NAME: AITuner4
      SWIFT_VERSION: "5.7"
      TARGETED_DEVICE_FAMILY: "1,2" # iPhone and iPad
      INFOPLIST_FILE: AITuner4/Resources/Info.plist
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
